modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license='''
MIT License
Copyright (c) 2021 GLEEP ORANGE
'''
issueTrackerURL="https://github.com/GL33P-0R4NG3/oreganized/issues/" #optional

[[mods]] #mandatory
modId="oreganized" #mandatory
version="1.16.4-0.4.2-beta" #mandatory
displayName="Oreganized Mod" #mandatory
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/oreganized-mod/files" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreganized-mod" #optional
logoFile="oreganized.png" #optional
credits="Thanks for this Oreganized mod goes to our active () members on our discord server!" #optional
authors="<Gl33p_0r4ange>, Agent M" #optional
description='''
Expands vanilla stuff.
'''

[[dependencies.oreganized]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.oreganized]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
